"""initial schema

Generated with `flask db migrate`, then edited by hand:
- CHECK constraints: wallet balance >= 0, amounts > 0, status/source/outcome/topic enums,
  msisdn format (all named through the metadata naming convention).
- Unique keys: topups.deposit_id, ledger_entries (topup_id, kind) which makes a second credit
  for the same top-up impossible, outbox.dedupe_key, wallet_accounts (customer_id, currency),
  topups (customer_id, idempotency_key).
- ledger_entries is append-only: a PL/pgSQL BEFORE UPDATE OR DELETE trigger raises.
  Corrections are new entries, never edits.

Revision ID: 86c9ed002751
Revises:
Create Date: 2026-10-03 10:13:10.849120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

LEDGER_APPEND_ONLY_FUNCTION = """
CREATE OR REPLACE FUNCTION ledger_entries_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'ledger_entries is append-only: % is not allowed, post a new entry instead', TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$;
"""

LEDGER_APPEND_ONLY_TRIGGER = """
CREATE TRIGGER ledger_entries_append_only
BEFORE UPDATE OR DELETE ON ledger_entries
FOR EACH ROW EXECUTE FUNCTION ledger_entries_append_only();
"""

# revision identifiers, used by Alembic.
revision = '86c9ed002751'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("topic IN ('receipt.issued', 'voip_credit.granted')", name=op.f('ck_outbox_topic_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_outbox_dedupe_key'))
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index('ix_outbox_pending', ['created_at'], unique=False, postgresql_where=sa.text('delivered_at IS NULL'))

    op.create_table('reconcile_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('settled', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('still_open', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_not_found', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('errors', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("trigger IN ('schedule', 'manual', 'eb_cron')", name=op.f('ck_reconcile_runs_trigger_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconcile_runs'))
    )
    op.create_table('topups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deposit_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('country', sa.CHAR(length=3), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('msisdn', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'CREATED'"), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('provider_txn_id', sa.String(length=128), nullable=True),
    sa.Column('scenario', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("msisdn ~ '^[1-9][0-9]{7,14}$'", name=op.f('ck_topups_msisdn_format')),
    sa.CheckConstraint("status IN ('CREATED', 'ACCEPTED', 'PROCESSING', 'IN_RECONCILIATION', 'COMPLETED', 'FAILED', 'REJECTED', 'NEEDS_ATTENTION')", name=op.f('ck_topups_status_valid')),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_topups_amount_positive')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_topups_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topups')),
    sa.UniqueConstraint('customer_id', 'idempotency_key', name=op.f('uq_topups_customer_id_idempotency_key')),
    sa.UniqueConstraint('deposit_id', name=op.f('uq_topups_deposit_id'))
    )
    with op.batch_alter_table('topups', schema=None) as batch_op:
        batch_op.create_index('ix_topups_customer_created', ['customer_id', 'created_at'], unique=False)
        batch_op.create_index('ix_topups_msisdn_created', ['msisdn', 'created_at'], unique=False)
        batch_op.create_index('ix_topups_open_created', ['created_at'], unique=False, postgresql_where=sa.text("status IN ('CREATED', 'ACCEPTED', 'PROCESSING', 'IN_RECONCILIATION')"))

    op.create_table('wallet_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('balance_minor', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_minor >= 0', name=op.f('ck_wallet_accounts_balance_non_negative')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_wallet_accounts_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_accounts')),
    sa.UniqueConstraint('customer_id', 'currency', name=op.f('uq_wallet_accounts_customer_id_currency'))
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('topup_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('topup_credit')", name=op.f('ck_ledger_entries_kind_valid')),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_ledger_entries_amount_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['wallet_accounts.id'], name=op.f('fk_ledger_entries_account_id_wallet_accounts')),
    sa.ForeignKeyConstraint(['topup_id'], ['topups.id'], name=op.f('fk_ledger_entries_topup_id_topups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries')),
    sa.UniqueConstraint('topup_id', 'kind', name=op.f('uq_ledger_entries_topup_id_kind'))
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_account_id'), ['account_id'], unique=False)

    op.create_table('payment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topup_id', sa.UUID(), nullable=True),
    sa.Column('deposit_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(length=16), server_default=sa.text("'not_checked'"), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('applied', 'duplicate_ignored', 'rejected', 'held_for_review', 'no_change', 'error')", name=op.f('ck_payment_events_outcome_valid')),
    sa.CheckConstraint("signature IN ('verified', 'invalid', 'missing', 'not_checked')", name=op.f('ck_payment_events_signature_valid')),
    sa.CheckConstraint("source IN ('initiate_response', 'callback', 'status_check', 'reconcile', 'replay', 'forged_test', 'resend_request')", name=op.f('ck_payment_events_source_valid')),
    sa.ForeignKeyConstraint(['topup_id'], ['topups.id'], name=op.f('fk_payment_events_topup_id_topups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_events'))
    )
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.create_index('ix_payment_events_created', ['created_at'], unique=False)
        batch_op.create_index('ix_payment_events_topup_created', ['topup_id', 'created_at'], unique=False)

    # ### end Alembic commands ###

    # Hand-written: the ledger is append-only.
    op.execute(LEDGER_APPEND_ONLY_FUNCTION)
    op.execute(LEDGER_APPEND_ONLY_TRIGGER)


def downgrade():
    op.execute("DROP TRIGGER IF EXISTS ledger_entries_append_only ON ledger_entries")
    op.execute("DROP FUNCTION IF EXISTS ledger_entries_append_only()")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_events_topup_created')
        batch_op.drop_index('ix_payment_events_created')

    op.drop_table('payment_events')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_account_id'))

    op.drop_table('ledger_entries')
    op.drop_table('wallet_accounts')
    with op.batch_alter_table('topups', schema=None) as batch_op:
        batch_op.drop_index('ix_topups_open_created', postgresql_where=sa.text("status IN ('CREATED', 'ACCEPTED', 'PROCESSING', 'IN_RECONCILIATION')"))
        batch_op.drop_index('ix_topups_msisdn_created')
        batch_op.drop_index('ix_topups_customer_created')

    op.drop_table('topups')
    op.drop_table('reconcile_runs')
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index('ix_outbox_pending', postgresql_where=sa.text('delivered_at IS NULL'))

    op.drop_table('outbox')
    op.drop_table('customers')
    # ### end Alembic commands ###
